site_name: Zipformer
site_url: https://pkufool.github.io/zipformer
site_description: A faster and better encoder for ASR

docs_dir: 'docs/en'
site_dir: 'site'

repo_name: pkufool/zipformer
repo_url: https://github.com/pkufool/zipformer

copyright: Copyright &copy; 2019 - 2026 Next-Gen Kaldi Team (XiaoMi AI Lab)

theme:
  name: material
  logo: assets/pic/k2.png
  favicon: assets/pic/k2.png
  language: en
  custom_dir: docs/custom
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link

nav:
  - Getting Started:
    - Introduction: index.md
    - Models: models.md
    - Training: training.md
    - Deployment: deployment.md
  - API Reference: api/index.md
  - Message: message.md

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
        - ja
        - zh
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css

extra:
  alternate:  
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pkufool/zipformer
