site_name: Zipformer
site_url: https://pkufool.github.io/zipformer
site_description: A faster and better encoder for ASR

repo_name: pkufool/zipformer
repo_url: https://github.com/pkufool/zipformer

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - API Reference: api.md
  - Message: guestbook.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ja
        - zh
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pkufool/zipformer
